name: Deploy to AWS

on:
  push:
    branches:
      - main # Muda se a sua branch principal tiver outro nome

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Acessando servidor e atualizando
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd ~/frontend-progest-base
            git fetch origin
            git reset --hard origin/main
            docker compose -f docker-compose.aws.yml up -d --build